[[edge_functions]]
path     = "/og"
function = "og"

[[headers]]
  for = "/robots.txt"
  [headers.values]
  Cache-Control = "public, max-age=0, s-maxage=600"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
  Cache-Control = "public, max-age=0, s-maxage=600"